baseURL = "http://example.org/"
languageCode = "fi"
theme = "terminal"
title = "Vammala Party"
[params]
centerTheme = true
contentTypeName = "posts"
fullWidthTheme = false
readMore = "Lue lisää"
showLanguageSelector = false
showMenuItems = 2
themeColor = "pink"
[params.logo]
logoText = "Vammala Party"
